theme: jekyll-theme-minimal

logo: ./logo.png
description: >
  This page contain two of my projects relating to data science/machine learning.
  The first project is an outreach project for NYC's local non-profit organization CityHarvest 
  on the subject of food insecurity. The second project is a machine generated spin off issue of 
  the Cooper Pioneer, the school newspaper.
  
  sdf hfduh;eig
  <br><br>
  <a href='https://raymondminglee.github.io'>Back to homepage</a>
